# AWS harness shared by every raft product under test (braft/, and any
# future sibling directory). Provisions the EC2 fleet; each product's own
# Makefile (e.g. braft/Makefile) handles build/push/start/benchmark against
# whatever this deploys. Config comes from .env (generated by `make env`,
# not checked into git).
-include .env
include common.mk

# Required by deploy/main.tf's ssh_ingress_cidr variable (no default there,
# so terraform prompts for it on every plan-affecting command otherwise,
# including destroy). Set in .env; update it if your IP changes.
export TF_VAR_ssh_ingress_cidr := $(SSH_INGRESS_CIDR)

# single_az: all 4 instances in one cluster placement group/AZ.
# multi_az: raft nodes spread across deploy/multi_az.tfvars' node_azs, with
# node[0]/NODE1 sharing the client's AZ + placement group.
# multi_az is the default: a single-AZ cluster understates replication latency by
# removing the cross-AZ round trip that any production raft deployment pays, so
# every published number here is measured multi-AZ. single_az remains available
# for isolating what that round trip costs.
TOPOLOGY ?= multi_az
# Relative to deploy/, since terraform -chdir=deploy resolves -var-file from there.
TFVARS    = $(TOPOLOGY).tfvars

.PHONY: deploy plan destroy env node-rtt

## Create/update the EC2 fleet for $(TOPOLOGY) (switch with make deploy TOPOLOGY=single_az)
deploy:
	terraform -chdir=deploy init
	terraform -chdir=deploy apply -var-file=$(TFVARS)

## Read-only: show what switching to $(TOPOLOGY) would change, without applying
plan:
	terraform -chdir=deploy init
	terraform -chdir=deploy plan -var-file=$(TFVARS)

destroy:
	terraform -chdir=deploy destroy -var-file=$(TFVARS)

## Write instance IPs from terraform state into .env
env:
	terraform -chdir=deploy output -raw env_file > .env
	@cat .env

## Measure real inter-node RTT; works in any topology (same PG or spread
## across AZs). In multi_az, AWS doesn't publish which AZs are physically
## closest, so check empirically rather than assume node_azs in multi_az.tfvars
## is the best pick — swap in a different AZ from the remaining three if one
## leg is a clear outlier.
node-rtt:
	@for h in $(NODE1):$(NODE2_PRIV),$(NODE3_PRIV) $(NODE2):$(NODE1_PRIV),$(NODE3_PRIV) $(NODE3):$(NODE1_PRIV),$(NODE2_PRIV); do \
		host=$${h%%:*}; targets=$${h##*:}; \
		echo "=== from $$host ==="; \
		ssh $(SSH_OPTS) $(SSH_USER)@$$host "for t in $$(echo $$targets | tr ',' ' '); do ping -c 20 -q \$$t | tail -2; done" ; \
	done

# ---------------------------------------------------------------------------
# Charts. Every chart in README.md is regenerated from the raw sweep CSVs, so
# a reader can recheck any number and rebuild any figure. mkcharts.py takes any
# number of CSVs (rows carry their own `product` column), which is what lets the
# cross-round-trip comparison see all of sequencer's phases at once.
#
# CHART_CSVS is deliberately a wildcard over each product's own sweep output
# plus the historical sweep/knee-sweep.csv: a product whose sweep hasn't been
# re-run yet simply keeps its committed curve, rather than vanishing from the
# combined chart.
CHART_CSVS ?= sweep/knee-sweep.csv \
              $(wildcard braft/braft.csv) $(wildcard aeron/aeron.csv) \
              $(wildcard openraft/openraft.csv) \
              $(wildcard sequencer/seq.csv) $(wildcard sequencer/seq-relay.csv) \
              $(wildcard sequencer/seq-output.csv)

.PHONY: charts sweep-products
charts:
	python3 sweep/mkcharts.py $(CHART_CSVS) .

## Re-run all three non-sequencer products' sweeps, in sequence — they share
## one fleet, so they cannot overlap. Each brings its own cluster up first.
## sequencer/ has its own `make sweep-all` (five round trips) — deliberately
## separate, since it is the only product with more than one.
sweep-products:
	$(MAKE) -C braft push start
	sleep 5
	$(MAKE) -C braft sweep
	$(MAKE) -C openraft push start
	sleep 5
	$(MAKE) -C openraft sweep
	$(MAKE) -C aeron push start
	sleep 10
	$(MAKE) -C aeron sweep
