# AWS harness shared by every raft product under test (braft/, and any
# future sibling directory). Provisions the EC2 fleet; each product's own
# Makefile (e.g. braft/Makefile) handles build/push/start/benchmark against
# whatever this deploys. Config comes from .env (generated by `make env`,
# not checked into git).
-include .env
include common.mk

# Required by deploy/main.tf's ssh_ingress_cidr variable (no default there,
# so terraform prompts for it on every plan-affecting command otherwise,
# including destroy). Set in .env; update it if your IP changes.
export TF_VAR_ssh_ingress_cidr := $(SSH_INGRESS_CIDR)

# single_az: all 4 instances in one cluster placement group/AZ.
# multi_az: raft nodes spread across deploy/multi_az.tfvars' node_azs, with
# node[0]/NODE1 sharing the client's AZ + placement group.
# multi_az is the default: a single-AZ cluster understates replication latency by
# removing the cross-AZ round trip that any production raft deployment pays, so
# every published number here is measured multi-AZ. single_az remains available
# for isolating what that round trip costs.
TOPOLOGY ?= multi_az
# Relative to deploy/, since terraform -chdir=deploy resolves -var-file from there.
TFVARS    = $(TOPOLOGY).tfvars

.PHONY: deploy deploy-multi deploy-multi-unattended start-instances stop-instances plan destroy env node-rtt

# How many load-generator/input-gateway boxes to provision. 1 is the
# historical fleet. Passed on every apply, so whichever value you use
# is the value the fleet ends up at — running plain `make deploy` after
# `make deploy-multi` WILL destroy the extra clients, which is the
# intended way to shrink back.
# Default to however many clients terraform state actually has, not a
# fixed 1: `make env` passes CLIENT_COUNT into a refresh, and refreshing
# a 5-client fleet with the historical default of 1 renders an .env
# naming a single client, silently turning a five-gateway sweep into a
# one-gateway sweep. Falls back to 1 before the first apply, when there
# is no state to count.
CLIENT_COUNT ?= $(or $(shell terraform -chdir=deploy state list 2>/dev/null | grep -c '^aws_instance\.client\[' | grep -v '^0$$'),1)
# aws-cli calls here are region-scoped; deploy/main.tf pins the same one.
AWS_REGION ?= us-east-1

## Create/update the EC2 fleet for $(TOPOLOGY) (switch with make deploy TOPOLOGY=single_az)
deploy:
	terraform -chdir=deploy init
	terraform -chdir=deploy apply -var-file=$(TFVARS) -var client_count=$(CLIENT_COUNT)

## The input-gateway scale fleet: 3 nodes + $(MULTI_CLIENT_COUNT) clients, every
## client in the same cluster placement group and AZ as node[0] — the
## same scheme the single client always used. A separate target because
## it is a specific experiment (several input gateways sharing traffic
## to one leader), not the default shape.
##
## At 8 vCPU per box this is 3*8 + 5*8 = 64 vCPU, the entire on-demand
## quota, so nothing else can run alongside it. Shrink back with
## `make deploy` (CLIENT_COUNT defaults to 1).
MULTI_CLIENT_COUNT ?= 5
deploy-multi:
	$(MAKE) deploy CLIENT_COUNT=$(MULTI_CLIENT_COUNT)

## Same fleet, applied without the interactive "yes". Not a bare
## -auto-approve: it saves the plan, refuses it if anything would be
## destroyed or replaced (deploy/assert-safe-plan.py), and only then
## applies that exact saved plan. The prompt mostly guards against a
## plan quietly becoming a teardown, and that is the case this checks --
## it caught a provider-side AMI change that would have replaced the
## whole fleet. For a deliberate teardown use `make destroy`.
deploy-multi-unattended:
	terraform -chdir=deploy init -input=false
	terraform -chdir=deploy plan -input=false -var-file=$(TFVARS) \
		-var client_count=$(MULTI_CLIENT_COUNT) -out=tfplan
	terraform -chdir=deploy show -json tfplan | python3 deploy/assert-safe-plan.py
	terraform -chdir=deploy apply -input=false tfplan
	rm -f deploy/tfplan
	$(MAKE) env

## Start every stopped instance and block until all are running. A
## terraform apply creates new instances running but leaves existing
## stopped ones alone, so a fleet brought back from stopped needs this.
start-instances:
	@ids=$$(aws ec2 describe-instances --region $(AWS_REGION) \
		--filters 'Name=instance-state-name,Values=stopped' \
		--query 'Reservations[].Instances[].InstanceId' --output text); \
	if [ -n "$$ids" ]; then echo "starting: $$ids"; \
		aws ec2 start-instances --region $(AWS_REGION) --instance-ids $$ids >/dev/null; \
	else echo "nothing stopped"; fi
	@echo "waiting for all instances to reach running..."
	@until [ -z "$$(aws ec2 describe-instances --region $(AWS_REGION) \
		--filters 'Name=instance-state-name,Values=pending,stopping,stopped' \
		--query 'Reservations[].Instances[].InstanceId' --output text)" ]; do sleep 10; done
	@aws ec2 describe-instances --region $(AWS_REGION) \
		--query 'Reservations[].Instances[].{N:Tags[?Key==`Name`]|[0].Value,T:InstanceType,S:State.Name}' \
		--output table

## Stop every running instance -- compute billing ceases, disks survive.
stop-instances:
	@ids=$$(aws ec2 describe-instances --region $(AWS_REGION) \
		--filters 'Name=instance-state-name,Values=running' \
		--query 'Reservations[].Instances[].InstanceId' --output text); \
	if [ -n "$$ids" ]; then aws ec2 stop-instances --region $(AWS_REGION) --instance-ids $$ids >/dev/null; \
		echo "stopping: $$ids"; else echo "nothing running"; fi

## Read-only: show what switching to $(TOPOLOGY) would change, without applying
plan:
	terraform -chdir=deploy init
	terraform -chdir=deploy plan -var-file=$(TFVARS)

destroy:
	terraform -chdir=deploy destroy -var-file=$(TFVARS)

## Write instance IPs from terraform state into .env
env:
	@# Refresh first: terraform stores whatever the public IPs were at the
	@# last apply, and a stopped instance has none. Bringing a fleet back
	@# from stopped and running `make env` straight after therefore wrote
	@# an .env full of empty hostnames.
	terraform -chdir=deploy refresh -var-file=$(TFVARS) -var client_count=$(CLIENT_COUNT) >/dev/null
	terraform -chdir=deploy output -raw env_file > .env
	@cat .env

## Measure real inter-node RTT; works in any topology (same PG or spread
## across AZs). In multi_az, AWS doesn't publish which AZs are physically
## closest, so check empirically rather than assume node_azs in multi_az.tfvars
## is the best pick — swap in a different AZ from the remaining three if one
## leg is a clear outlier.
node-rtt:
	@for h in $(NODE1):$(NODE2_PRIV),$(NODE3_PRIV) $(NODE2):$(NODE1_PRIV),$(NODE3_PRIV) $(NODE3):$(NODE1_PRIV),$(NODE2_PRIV); do \
		host=$${h%%:*}; targets=$${h##*:}; \
		echo "=== from $$host ==="; \
		ssh $(SSH_OPTS) $(SSH_USER)@$$host "for t in $$(echo $$targets | tr ',' ' '); do ping -c 20 -q \$$t | tail -2; done" ; \
	done

# ---------------------------------------------------------------------------
# Charts. Every chart in README.md is regenerated from the raw sweep CSVs, so
# a reader can recheck any number and rebuild any figure. mkcharts.py takes any
# number of CSVs (rows carry their own `product` column), which is what lets the
# cross-round-trip comparison see all of sequencer's phases at once.
#
# Only current-fleet CSVs. mkcharts.py averages rows sharing a product and
# rate, so mixing fleets silently produces a curve that is neither: feeding it
# both the c6i and c7a braft rows drew a "knee" at 165k that exists in neither
# dataset. sweep/knee-sweep-c6i.csv is kept for provenance and deliberately NOT
# listed here — chart it on its own if you want the old fleet's shape.
CHART_CSVS ?= $(wildcard braft/braft.csv) $(wildcard aeron/aeron.csv) \
              $(wildcard openraft/openraft.csv) \
              $(wildcard sequencer/seq.csv) $(wildcard sequencer/seq-relay.csv) \
              $(wildcard sequencer/seq-output.csv)

.PHONY: charts sweep-products
charts:
	python3 sweep/mkcharts.py $(CHART_CSVS) .

## Re-run all three non-sequencer products' sweeps, in sequence — they share
## one fleet, so they cannot overlap. Each brings its own cluster up first and
## then WAITS for it to actually be serving before sweeping.
##
## That wait is not cosmetic. A sweep started while only some nodes are up
## measures a cluster with no quorum: the first attempt at this produced a
## 23-second p50 and 360 unsent requests at 10k, which looks like a product
## result and is really just "one of three nodes had started." Each product's
## check below is the cheapest thing that distinguishes the two.
sweep-products:
	$(MAKE) -C braft push start
	@echo "waiting for braft quorum..."
	@for h in $(NODE1) $(NODE2) $(NODE3); do \
		until [ "$$(ssh $(SSH_OPTS) $(SSH_USER)@$$h 'pgrep -c atomic_server || echo 0')" != "0" ]; do sleep 2; done ; \
	done; sleep 5
	$(MAKE) -C braft sweep
	$(MAKE) -C openraft push start
	@sleep 5
	$(MAKE) -C openraft init-cluster
	@sleep 3
	$(MAKE) -C openraft sweep
	$(MAKE) -C aeron provision push start
	@echo "waiting for aeron cluster..."
	@sleep 20
	$(MAKE) -C aeron sweep
