# AWS harness shared by every raft product under test (braft/, and any
# future sibling directory). Provisions the EC2 fleet; each product's own
# Makefile (e.g. braft/Makefile) handles build/push/start/benchmark against
# whatever this deploys. Config comes from .env (generated by `make env`,
# not checked into git).
-include .env
include common.mk

# Required by deploy/main.tf's ssh_ingress_cidr variable (no default there,
# so terraform prompts for it on every plan-affecting command otherwise,
# including destroy). Set in .env; update it if your IP changes.
export TF_VAR_ssh_ingress_cidr := $(SSH_INGRESS_CIDR)

# single_az: all 4 instances in one cluster placement group/AZ.
# multi_az: raft nodes spread across deploy/multi_az.tfvars' node_azs, with
# node[0]/NODE1 sharing the client's AZ + placement group.
# multi_az is the default: a single-AZ cluster understates replication latency by
# removing the cross-AZ round trip that any production raft deployment pays, so
# every published number here is measured multi-AZ. single_az remains available
# for isolating what that round trip costs.
TOPOLOGY ?= multi_az
# Relative to deploy/, since terraform -chdir=deploy resolves -var-file from there.
TFVARS    = $(TOPOLOGY).tfvars

.PHONY: deploy plan destroy env node-rtt

## Create/update the EC2 fleet for $(TOPOLOGY) (switch with make deploy TOPOLOGY=single_az)
deploy:
	terraform -chdir=deploy init
	terraform -chdir=deploy apply -var-file=$(TFVARS)

## Read-only: show what switching to $(TOPOLOGY) would change, without applying
plan:
	terraform -chdir=deploy init
	terraform -chdir=deploy plan -var-file=$(TFVARS)

destroy:
	terraform -chdir=deploy destroy -var-file=$(TFVARS)

## Write instance IPs from terraform state into .env
env:
	terraform -chdir=deploy output -raw env_file > .env
	@cat .env

## Measure real inter-node RTT; works in any topology (same PG or spread
## across AZs). In multi_az, AWS doesn't publish which AZs are physically
## closest, so check empirically rather than assume node_azs in multi_az.tfvars
## is the best pick — swap in a different AZ from the remaining three if one
## leg is a clear outlier.
node-rtt:
	@for h in $(NODE1):$(NODE2_PRIV),$(NODE3_PRIV) $(NODE2):$(NODE1_PRIV),$(NODE3_PRIV) $(NODE3):$(NODE1_PRIV),$(NODE2_PRIV); do \
		host=$${h%%:*}; targets=$${h##*:}; \
		echo "=== from $$host ==="; \
		ssh $(SSH_OPTS) $(SSH_USER)@$$host "for t in $$(echo $$targets | tr ',' ' '); do ping -c 20 -q \$$t | tail -2; done" ; \
	done
